apiVersion: v1
kind: Service
metadata:
  name: mars-exploration-rovers-master
  labels:
    app: mars-exploration-rovers-master
    role: master
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: mars-exploration-rovers-master
    role: master
    tier: backend